server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          enabled: true
          register: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**


logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0  # Trace 100% of requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"   # expose all endpoints (use caution in prod) or "health", "info"
  endpoint:
    health:
      show-details: always

