server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose all endpoints (use caution in prod)
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0  # Trace 100% of requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

